"""
calendar_grid.py

Builds the Jinja2 render context for one month, reproducing the layout of the
static PNG generated by app/image.py (from the `absences` repo) but as data for
a CSS-grid HTML table instead of a pixel image.

Layout (mirrors image.py):
  * 1 label column (250px)  +  31 day columns (25px each)
  * Row 1 : CW (ISO week) bars, drawn only over week-days (Mon-Fri)
  * Row 2 : day numbers (weekend cells shaded, holidays magenta)
  * Rows 3.. : one row per "object" (person / resource), with absences coloured

Colours are taken verbatim from image.py:
  img_color        (192,176,192) -> #c0b0c0  base background
  weekend fill     #a090a0
  CW bar fill      #ba90ba
  holiday fill     #e121ff
  padding fill     #605060  (columns of days that don't exist, e.g. 31 in a 30-day month)
  grid lines       #808080
  current title    #2020ff
  white boxes      #ffffff
"""

from __future__ import annotations

import calendar
from datetime import date
from typing import Iterable, Optional


# --- colours (straight from image.py) --------------------------------------
COL_BASE = "#c0b0c0"
COL_WEEKEND = "#a090a0"
COL_CW = "#ba90ba"
COL_HOLIDAY = "#e121ff"
COL_PAD = "#605060"

TOTAL_DAY_COLS = 31  # the grid is always 31 columns wide (fixed width), like the PNG


def _truncate(text: str, max_chars: int) -> str:
    """Rough client-side truncation so long captions don't overflow a cell.

    The real width limiting is done by CSS (overflow:hidden); this just keeps
    the title tooltip / text sensible.
    """
    if not text:
        return ""
    return text if len(text) <= max_chars else text[:max_chars]


def _cw_segments(year: int, month: int, num_days: int) -> list[dict]:
    """Group consecutive week-days (Mon-Fri) of the same ISO week into a bar.

    Returns a list of {start, end, week, span}. Weekend days are excluded, which
    naturally breaks the segments exactly the way image.py draws its CW boxes.
    """
    segments: list[dict] = []
    cur: Optional[dict] = None
    for d in range(1, num_days + 1):
        dt = date(year, month, d)
        if dt.weekday() < 5:  # Mon..Fri
            week = dt.isocalendar().week
            if cur and cur["week"] == week and d == cur["end"] + 1:
                cur["end"] = d
            else:
                if cur:
                    segments.append(cur)
                cur = {"start": d, "end": d, "week": week}
    if cur:
        segments.append(cur)
    for s in segments:
        s["span"] = s["end"] - s["start"] + 1
    return segments


def build_context(
    year: int,
    month: int,
    objects: Iterable[str],
    absences: Optional[list[dict]] = None,
    holidays: Optional[dict] = None,
    today: Optional[date] = None,
) -> dict:
    """Assemble everything the template needs to draw the month.

    Parameters
    ----------
    year, month : int
    objects     : ordered iterable of row labels (people / resources)
    absences    : list of dicts, each:
                    {"object": <row label>  OR  "row": <0-based index>,
                     "day": int, "duration": int (default 1),
                     "color": "#rrggbb", "caption": str}
    holidays    : {day:int -> description:str}
    today       : override "today" (defaults to date.today())
    """
    objects = list(objects)
    absences = absences or []
    holidays = holidays or {}
    today = today or date.today()

    num_days = calendar.monthrange(year, month)[1]
    is_current_month = (month == today.month and year == today.year)
    current_day = today.day if is_current_month else None

    def is_weekend(d: int) -> bool:
        return date(year, month, d).weekday() >= 5

    # ---- Row 1 : CW bars + weekend shading + right-hand padding ----------
    segments = _cw_segments(year, month, num_days)
    seg_start = {s["start"]: s for s in segments}

    cw_cells: list[dict] = []
    for d in range(1, TOTAL_DAY_COLS + 1):
        col = d + 1  # grid column line (col 1 is the label column)
        if d > num_days:
            cw_cells.append(
                {"kind": "pad", "col_start": col, "col_end": col + 1,
                 "text": "", "color": COL_PAD, "title": ""}
            )
        elif is_weekend(d):
            cw_cells.append(
                {"kind": "weekend", "col_start": col, "col_end": col + 1,
                 "text": "", "color": COL_WEEKEND, "title": ""}
            )
        elif d in seg_start:
            s = seg_start[d]
            label = f"CW {s['week']}" if s["span"] >= 2 else ""
            cw_cells.append(
                {"kind": "cw", "col_start": d + 1, "col_end": s["end"] + 2,
                 "text": label, "color": COL_CW, "title": label}
            )
        # else: a week-day covered by a segment that already started -> skip

    # ---- Row 2 : day numbers --------------------------------------------
    day_cells: list[dict] = []
    for d in range(1, TOTAL_DAY_COLS + 1):
        col = d + 1
        if d > num_days:
            day_cells.append(
                {"kind": "pad", "col": col, "text": "", "color": COL_PAD, "title": ""}
            )
        else:
            if d in holidays:
                color = COL_HOLIDAY
            elif is_weekend(d):
                color = COL_WEEKEND
            else:
                color = COL_BASE
            day_cells.append(
                {"kind": "day", "col": col, "text": str(d), "color": color,
                 "title": holidays.get(d, "")}
            )

    # ---- Rows 3.. : object rows with absences ---------------------------
    object_rows: list[dict] = []
    for idx, name in enumerate(objects):
        by_day: dict[int, dict] = {}
        for a in absences:
            if a.get("object") == name or a.get("row") == idx:
                by_day[a["day"]] = a

        cells: list[dict] = []
        covered_until = 0
        for d in range(1, TOTAL_DAY_COLS + 1):
            col = d + 1
            if d <= covered_until:
                continue
            if d > num_days:
                cells.append(
                    {"kind": "pad", "col_start": col, "col_end": col + 1,
                     "text": "", "color": COL_PAD, "title": ""}
                )
            elif d in by_day:
                a = by_day[d]
                dur = int(a.get("duration", 1) or 1)
                end_day = min(d + dur - 1, num_days)
                caption = _truncate(a.get("caption", ""), max(1, (end_day - d + 1) * 3))
                cells.append(
                    {"kind": "abs", "col_start": col, "col_end": end_day + 2,
                     "text": caption, "color": a.get("color", COL_BASE),
                     "title": a.get("caption", "")}
                )
                covered_until = end_day
            else:
                color = COL_WEEKEND if is_weekend(d) else COL_BASE
                cells.append(
                    {"kind": "day", "col_start": col, "col_end": col + 1,
                     "text": "", "color": color, "title": ""}
                )
        object_rows.append({"name": name, "cells": cells})

    return {
        "month_name": date(year, month, 1).strftime("%B"),
        "year": year,
        "month": month,
        "num_days": num_days,
        "num_rows": len(objects),
        "total_cols": TOTAL_DAY_COLS,
        "cw_cells": cw_cells,
        "day_cells": day_cells,
        "object_rows": object_rows,
        "is_current_month": is_current_month,
        "current_day": current_day,
        # grid-row where the object block ends (used by the current-day box)
        "last_grid_row": len(objects) + 3,  # exclusive end line
    }
